server:
  port: 5000

spring:
  datasource:
    url: jdbc:h2:file:c:\Users\Ethanium\bankingpro
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

#spring:
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true